name: CI
'on':
  push: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #added
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt


# steps:
# - uses: actions/checkout@v4
# - uses: actions/setup-python@v5
#   with:
#     python-version: '3.10' 
# - run: python my_script.py